sudo: required
services: 
  - docker 

before_install: 
  - docker build -t suissitakwa/react-test -f ./client/Dockerfile.dev ./client
script: 
  - docker run -e CI=true suissitakwa/react-test npm run test 

after_success:
  - docker build -t  suissitakwa/multi-client ./client 
  - docker build -t  suissitakwa/multi-nginx ./nginx 
  - docker build -t  suissitakwa/multi-server ./server
  - docker build -t  suissitakwa/multi-worker ./worker  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push suissitakwa/multi-client
  - docker push suissitakwa/multi-nginx
  - docker push suissitakwa/multi-server
  - docker push suissitakwa/multi-worker
